SELECT *
FROM Person.Person
ORDER BY FirstName asc


/* DESAFIO
OBTER O PRODUCTid DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO O MAIS CARO PARA O MAIS BARATO
*/
SELECT*
FROM Production.Product

SELECT TOP 10 productId
FROM Production.Product
ORDER BY ListPrice desc

/*DESAFIO 20
OBTER O NOME E NUMERO DO PRODUTO DOS PRODUTOS QUE TEM O PRODUCTID ENTE 1 E 4
*/

SELECT TOP 4 name, ProductNumber
FROM Production.Product
ORDER BY ProductID asc