SELECT *
FROM person.Person
WHERE BusinessEntityID IN (2,7,13)

--O COMANDO NOT É UTILIZADO PARA MOSTRAR O INVERSO, EXEMPLO "not in (2,7,13)"

-- ESSE COMANDO É ULTIO POIS MANTEM O CODIGO COM MENOS LINHAS E MAIS LIMPO, UTILIZANDO MENOS CONDIÇÕES

SELECT*
FROM person.Person
WHERE BusinessEntityID= 2
OR BusinessEntityID = 7
OR	BusinessEntityID =13

