/*DESAFIO 
--QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS(PRODUCTION.PRODUCT)*/

SELECT count (*)
FROM Production.Product


SELECT *
FROM Production.Product

/* PROCURAR QUANTOS TAMANHOS DE PRODUTOS TEMOS CASASTRADOS EM NOSSA TABELA*/

SELECT count (Size)
	FROM Production.Product